"""add admin_comment to users

Revision ID: 8ad87c1e31a1
Revises: 965df8d6b696
Create Date: 2026-01-22 21:26:15.371318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ad87c1e31a1"
down_revision: Union[str, Sequence[str], None] = "965df8d6b696"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("admin_comment", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "admin_comment")
    # ### end Alembic commands ###
